name: 'Playwright Tests'

on:
  push:
    branches: [main, master]

env:
  NODE_ENV: 'test'
jobs:
  Run_first_job:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22, 24]
    env:
      NODE_ENV: 'test2'    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        env:
          NODE_ENV: 'test3'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: List all files in repository
        if: always()
        run: |
          sleep 10
          ls -la

  Run_second_job:
    runs-on: alpine:3.18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Install browsers for Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
