name: 'Playwright Tests'

on:
  push:
    branches: [main, master]

  workflow_dispatch:
    inputs:
      environment:
          type: choice
          description: 'Choose the environment to run the tests'
          required: true
          default: 'dev'
          options:
            - 'dev'
            - 'staging'
      tags:
          description: 'Set any tags like: "@smoke" , "@222333", "@fast|@slow"'
          required: false
          default: ''
      trace:
          type: choice
          description: 'Choose trace option: on / off / retain-on-failure'
          required: false
          default: 'off'
          options:
            - 'retain-on-failure'
            - 'on'
            - 'off'

env:
  NODE_ENV: 'test'
jobs:
  Run_first_job:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22, 24]
    env:
      NODE_ENV: 'test2'    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        env:
          NODE_ENV: 'test3'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: List all files in repository
        if: always()
        run: |
          sleep 10
          ls -la

  Run_second_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Install browsers for Playwright
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload playwright report artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 5
      # publish unit test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            junit-report/*.xml
            junit-report/*.json
        
      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./playwright-report
